version: '3'

services:
  ### PHP-FPM ##############################################
  matching-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/matching
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  ### NGINX Server #########################################
  matching-nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/matching
    ports:
      - "9101:80"
    depends_on:
      - matching-php

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
